/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type GovernanceDocument = {
  _id: string;
  _type: "governanceDocument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: {
    ar?: string;
    en?: string;
  };
  category?:
    | "policies-disclosure"
    | "financial-statements"
    | "program-reports"
    | "regulations"
    | "annual-documents"
    | "general-meetings"
    | "board-minutes"
    | "general-members"
    | "beneficiary-satisfaction-survey"
    | "supporter-satisfaction-survey"
    | "employee-volunteer-satisfaction-survey"
    | "membership-candidacy-survey"
    | "stakeholder-satisfaction-results"
    | "new-board-election-program"
    | "association-staff";
  document?: {
    ar?: string;
    en?: string;
  };
};

export type GeneralMembers = {
  _id: string;
  _type: "general-members";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: {
    ar?: string;
    en?: string;
  };
  title?: {
    ar?: string;
    en?: string;
  };
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  socialLinks?: Array<{
    platform?: "twitter" | "linkedin";
    url?: string;
    _key: string;
  }>;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: {
    ar?: string;
    en?: string;
  };
  title?: {
    ar?: string;
    en?: string;
  };
  avatar?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  socialLinks?: Array<{
    platform?: "twitter" | "linkedin";
    url?: string;
    _key: string;
  }>;
};

export type News = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  slug?: Slug;
  shortDescription?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  socialLinks?: {
    instagram?: string;
    whatsapp?: string;
    linkedin?: string;
    twitter?: string;
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Carousel = {
  _id: string;
  _type: "carousel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  buttonText?: string;
  buttonUrl?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: string;
  name?: string;
  position?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | GovernanceDocument
  | GeneralMembers
  | Member
  | News
  | Slug
  | Carousel
  | Testimonial
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/news/getAllNews.ts
// Variable: NewsQUERY
// Query: *[_type == "news"] | order(_createdAt desc) {      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      slug,      shortDescription,      content,      image {        asset -> {          url        }      },      datePublished,      socialLinks    }
export type NewsQUERYResult = Array<{
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  datePublished: null;
  socialLinks: {
    instagram?: string;
    whatsapp?: string;
    linkedin?: string;
    twitter?: string;
  } | null;
}>;

// Source: ./sanity/lib/news/getAllNewsSlugs.ts
// Variable: ALL_Slugs_QUERY
// Query: *[_type == "news"] {      "slug": slug.current    }
export type ALL_Slugs_QUERYResult = Array<{
  slug: string | null;
}>;

// Source: ./sanity/lib/news/getSearchNewsTitles.ts
// Variable: ALL_NewsTitles_QUERY
// Query: *[_type == "news" && title match $searchQuery] | order(title desc)[0...10] {  title,  slug,  shortDescription,  image {    asset -> {      url    }  }  }
export type ALL_NewsTitles_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;

// Source: ./sanity/lib/news/getSingleNews.ts
// Variable: SingleNewsQuery
// Query: *[_type == "news" && slug.current == $slug][0] {      _id,      _type,      _createdAt,      _updatedAt,      _rev,      title,      slug,      shortDescription,      content,      image {        asset -> {          url        }      },      datePublished,      socialLinks {        instagram,        whatsapp,        twitter,        linkedin      }    }
export type SingleNewsQueryResult = {
  _id: string;
  _type: "news";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  shortDescription: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  image: {
    asset: {
      url: string | null;
    } | null;
  } | null;
  datePublished: null;
  socialLinks: {
    instagram: string | null;
    whatsapp: string | null;
    twitter: string | null;
    linkedin: string | null;
  } | null;
} | null;

// Source: ./sanity/lib/news/governanceDocument.ts
// Variable: ALL_GovernanceDocument_QUERY
// Query: *[_type == "governanceDocument" && category == $categoryFilter] {      _id,      category,      title {        ar,        en      },      document {        ar,        en      }    } | order(_createdAt desc)
export type ALL_GovernanceDocument_QUERYResult = Array<{
  _id: string;
  category:
    | "annual-documents"
    | "association-staff"
    | "beneficiary-satisfaction-survey"
    | "board-minutes"
    | "employee-volunteer-satisfaction-survey"
    | "financial-statements"
    | "general-meetings"
    | "general-members"
    | "membership-candidacy-survey"
    | "new-board-election-program"
    | "policies-disclosure"
    | "program-reports"
    | "regulations"
    | "stakeholder-satisfaction-results"
    | "supporter-satisfaction-survey"
    | null;
  title: {
    ar: string | null;
    en: string | null;
  } | null;
  document: {
    ar: string | null;
    en: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n    *[_type == "news"] | order(_createdAt desc) {\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      slug,\n      shortDescription,\n      content,\n      image {\n        asset -> {\n          url\n        }\n      },\n      datePublished,\n      socialLinks\n    }\n  ': NewsQUERYResult;
    '*[_type == "news"] {\n      "slug": slug.current\n    }\n  ': ALL_Slugs_QUERYResult;
    '*[_type == "news" && title match $searchQuery] | order(title desc)[0...10] {\n  title,\n  slug,\n  shortDescription,\n  image {\n    asset -> {\n      url\n    }\n  }\n  }': ALL_NewsTitles_QUERYResult;
    '\n    *[_type == "news" && slug.current == $slug][0] {\n      _id,\n      _type,\n      _createdAt,\n      _updatedAt,\n      _rev,\n      title,\n      slug,\n      shortDescription,\n      content,\n      image {\n        asset -> {\n          url\n        }\n      },\n      datePublished,\n      socialLinks {\n        instagram,\n        whatsapp,\n        twitter,\n        linkedin\n      }\n    }\n  ': SingleNewsQueryResult;
    '\n    *[_type == "governanceDocument" && category == $categoryFilter] {\n      _id,\n      category,\n      title {\n        ar,\n        en\n      },\n      document {\n        ar,\n        en\n      }\n    } | order(_createdAt desc)\n  ': ALL_GovernanceDocument_QUERYResult;
  }
}
