name: motqen-website
region: fra1
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/ryadh-sa/MotqenProduction.git
    build_command: pnpm install && pnpm run build
    run_command: node .next/standalone/server.js
    envs:
      - key: NEXT_PUBLIC_SANITY_PROJECT_ID
        value: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
      - key: NEXT_PUBLIC_SANITY_DATASET
        value: ${NEXT_PUBLIC_SANITY_DATASET}
      - key: NEXT_PUBLIC_BASE_URL
        value: ${NEXT_PUBLIC_BASE_URL}
      - key: NEXT_PUBLIC_SANITY_PERSPECTIVE
        value: ${NEXT_PUBLIC_SANITY_PERSPECTIVE}
      - key: NEXT_PUBLIC_SANITY_READ_TOKEN
        value: ${NEXT_PUBLIC_SANITY_READ_TOKEN}
      - key: SANITY_STUDIO_URL
        value: ${SANITY_STUDIO_URL}
      - key: SANITY_STUDIO_PROJECT_ID
        value: ${SANITY_STUDIO_PROJECT_ID}
      - key: SANITY_STUDIO_DATASET
        value: ${SANITY_STUDIO_DATASET}
      - key: SANITY_API_TOKEN
        value: ${SANITY_API_TOKEN}
      - key: SANITY_READ_TOKEN
        value: ${SANITY_READ_TOKEN}
      - key: RESEND_API_KEY
        value: ${RESEND_API_KEY}
      - key: RESEND_FROM_EMAIL
        value: ${RESEND_FROM_EMAIL}
      - key: CONTACT_EMAIL
        value: ${CONTACT_EMAIL}
      - key: CSRF_SECRET
        value: ${CSRF_SECRET}
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /
