export const HERO_CAROUSEL_FIXED_HEIGHT = 491;
export const STATICS_FIXED_HEIGHT = 548;
export const PROGRAMS_FIXED_HEIGHT = 486;
export const SAID_FIXED_HEIGHT = 345;
export const TEXTAREA_MAX_CHARACTER = 255;
